version: '3.8'

services:
    app:
        container_name: bujetio_php
        build:
            context: .deploy
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html
        env_file:
            - .env
        volumes:
            - ./:/var/www/html
            - .deploy/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - bujetio_app

    nginx:
        image: nginx:alpine
        container_name: bujetio_nginx
        restart: unless-stopped
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        volumes:
            - ./:/var/www
            - .deploy/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - bujetio_app

    db:
        image: mysql:8.0
        container_name: bujetio_db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - bujetio_app

    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: unless-stopped
        networks:
            - bujetio_app

volumes:
    db_data:
        driver: local

networks:
    bujetio_app:
        driver: bridge
